import { BusinessConfig } from '../business.config';

import { DEFAULT_RESTAURANT_PRESET } from '../presets/default-restaurant.preset';

export const COFFEE_ST_FITZ_CONFIG: BusinessConfig = {
  ...DEFAULT_RESTAURANT_PRESET as BusinessConfig,
  id: 'coffee-st-fitz-merida',
  name: 'Coffee St Fitz',
  tagline: 'Desayunos · Café · Pan del día',
  category: 'cafe',
  concept: `Coffee St Fitz es una cafetería de desayunos en Mérida con presencia pública activa y una propuesta centrada en café, pan del día, fruta, parfait, jugos, smoothies, chapatas, omelettes y crepas.
Para esta implementación se tomará como referencia la ubicación de Mérida que compartiste vía Google Maps, enfocando el sitio en una sucursal concreta y en una experiencia clara de menú, ubicación y contacto.`,
  brand: {
    primaryColor: 'oklch(0.62 0.14 55)',
    accentColor: 'oklch(0.72 0.12 95)',
    bgBase: 'oklch(0.98 0.01 95)',
    fontDisplay: 'Cormorant Garamond',
    fontBody: 'Satoshi',
    darkMode: false,
  },
  seo: {
    title: 'Coffee St Fitz Mérida — Cafetería y desayunos',
    description: 'Coffee St Fitz Mérida: cafetería y desayunos con café, pan del día, jugos, smoothies y opciones de brunch en Mérida, Yucatán.',
    keywords: ['coffee st fitz', 'cafetería mérida', 'desayunos mérida', 'brunch mérida', 'coffee shop montebello', 'cafetería city center mérida'],
    ogImage: '/assets/og-image.jpg',
    locale: 'es_MX',
    schemaType: 'CafeOrCoffeeShop',
  },
  hero: {
    headline: 'Coffee St Fitz\npara tus mañanas en Mérida',
    subheadline: 'Desayunos, comidas, jugos, cafés y pan recién horneado, todo en un solo lugar.',
    ctaLabel: 'Explorar menú',
    ctaSecondaryLabel: 'Ver ubicación',
    locationLabel: 'Mérida, Yucatán',
    scrollCueLabel: 'Explorar',
    backgroundImage: 'https://pplx-res.cloudinary.com/image/upload/pplx_search_images/16846c818c94510b67e365ec0211620aea8f3ec8.jpg',
    overlayOpacity: 0.35,
  },
  cta: {
    reservationLabel: 'Contactar',
    whatsappLabel: 'Escríbenos',
    stickyLabel: 'Menú',
  },
  navigation: {
    homeLabel: 'Inicio',
    menuLabel: 'Menú',
    aboutLabel: 'Concepto',
    contactLabel: 'Contacto',
  },
  footer: {
    copyrightLabel: 'Coffee St Fitz · Mérida, Yucatán',
    navigationHeading: 'Navegación',
    hoursHeading: 'Horarios',
    contactHeading: 'Contacto',
  },
  sectionCopy: {
    images: {
      heroBackground: 'https://pplx-res.cloudinary.com/image/upload/pplx_search_images/16846c818c94510b67e365ec0211620aea8f3ec8.jpg',
      conceptImage: 'https://pplx-res.cloudinary.com/image/upload/pplx_search_images/984d96b8440003663a02cc4c06a9f5c42733c74e.jpg',
      conceptImageAlt: 'Café servido en barra con estilo brunch',
      locationMapImage: 'https://pplx-res.cloudinary.com/image/upload/pplx_search_images/868abcd5b9188a785f9c6e572859ef4b3a75aae1.jpg',
      menuPageHeroImage: 'https://pplx-res.cloudinary.com/image/upload/pplx_search_images/1fd6971e568b92e044c950cb1cfb71f2c6d6c4ae.jpg',
      menuItemFallbackImage: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=400&auto=format&fit=crop&q=80',
      menuItemImages: {
        m1: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=400&auto=format&fit=crop&q=80',
        m2: 'https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=400&auto=format&fit=crop&q=80',
        m3: 'https://images.unsplash.com/photo-1513442542250-854d436a73f2?w=400&auto=format&fit=crop&q=80',
        m4: 'https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?w=400&auto=format&fit=crop&q=80',
        m5: 'https://images.unsplash.com/photo-1464306076886-da185f6a9d05?w=400&auto=format&fit=crop&q=80',
        m6: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=400&auto=format&fit=crop&q=80',
        m7: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400&auto=format&fit=crop&q=80',
        m8: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=400&auto=format&fit=crop&q=80',
        m9: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&auto=format&fit=crop&q=80',
        m10: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&auto=format&fit=crop&q=80',
        m11: 'https://images.unsplash.com/photo-1517705008128-361805f42e86?w=400&auto=format&fit=crop&q=80',
        m12: 'https://images.unsplash.com/photo-1464306076886-da185f6a9d05?w=400&auto=format&fit=crop&q=80'
      }
    },
    concept: {
      eyebrow: 'El concepto',
      heading: 'Una cafetería que debe convertir mejor que redes sociales',
      lead: 'La marca ya comunica desayunos, café gourmet, pan del día, fruta, parfait, jugos, smoothies, chapatas, omelettes y crepas; el sitio debe concentrar todo eso en una experiencia más clara y vendible.',
      body: 'La dirección visual debe sentirse cálida, luminosa y apetecible, con foco en intención de visita inmediata: ver menú, confirmar horario, abrir mapa y contactar en segundos.',
      foundedLabel: 'Sucursal Mérida',
    },
    menuHighlights: {
      eyebrow: 'Favoritos del menú',
      heading: 'Favoritos reales de Coffee St Fitz',
      subheading: 'Inspirado en lo que la marca comunica públicamente: desayunos completos, café, pan del día, jugos, smoothies, chilaquiles, chapatas, omelettes y opciones dulces y saladas.',
      fullMenuLabel: 'Explorar menú',
    },
    promotions: {
      eyebrow: 'Momentos para volver',
      heading: 'Promociones y antojos que sí se sienten Coffee St Fitz',
      validUntilPrefix: 'Disponible hasta',
    },
    gallery: {
      eyebrow: 'Así se vive',
      heading: 'Desayuno casero, café y una mañana bien resuelta',
      filters: [
        { id: 'all', label: 'Todo' },
        { id: 'food', label: 'Desayunos' },
        { id: 'drinks', label: 'Café y bebidas' },
        { id: 'interior', label: 'Espacio' },
      ],
    },
    testimonials: {
      eyebrow: 'Lo que atrae',
      heading: 'Señales públicas que ya validan la propuesta',
      subheading: 'Instagram, Facebook y listados externos ya prueban interés; ahora hace falta un sitio que ordene el tráfico y convierta mejor.',
      proofItems: [
        { value: '2', label: 'Sucursales visibles en Instagram' },
        { value: '7:30', label: 'Horario publicado entre semana' },
        { value: '999', label: 'Teléfono público visible' },
      ],
    },
    location: {
      eyebrow: 'Ubicación',
      heading: 'Ubica Coffee St Fitz en Mérida',
    },
    menuPage: {
      eyebrow: 'Café + desayuno',
      heading: 'Menú Coffee St Fitz',
      lead: 'Desayunos, café y opciones casuales diseñadas para una visita recurrente y una decisión rápida desde móvil.',
      finalHeading: '¿Listo para visitar Coffee St Fitz?',
      finalDescription: 'Menú, mapa, horario y contacto deben resolverse en una sola visita.',
    },
    contactPage: {
      eyebrow: 'Contacto rápido',
      heading: 'Contacto y ubicación',
      whatsappTitle: 'WhatsApp / teléfono',
      reservationTitle: 'Pedido o consulta',
      reservationDescription: 'Usa el formulario para simular contacto, pedido o consulta rápida',
      emailTitle: 'Sitio / contacto',
    },
  },
  menuCategories: [
    { id: 'desayunos', name: 'Desayunos', description: 'Opciones completas para empezar el día' },
    { id: 'dulce', name: 'Dulce', description: 'Hotcakes, waffles y antojos' },
    { id: 'salado', name: 'Salado', description: 'Brunch, sándwiches y platos fuertes ligeros' },
    { id: 'cafe', name: 'Café', description: 'Espresso, latte y bebidas especiales' },
    { id: 'frias', name: 'Frías', description: 'Smoothies, jugos y bebidas frescas' },
  ],
  menuItems: [
    { id: 'm1', categoryId: 'desayunos', name: 'Desayuno americano', description: 'Hotcakes, huevo al gusto y acompañamientos', price: '$185', tag: 'popular', featured: true },
    { id: 'm2', categoryId: 'desayunos', name: 'Huevos motuleños', description: 'Desayuno clásico muy recomendado en reseñas públicas de la marca', price: '$165', featured: true },
    { id: 'm3', categoryId: 'desayunos', name: 'Parfait de fruta', description: 'Yogurt, granola y fruta fresca', price: '$120' },
    { id: 'm4', categoryId: 'dulce', name: 'Hotcakes especiales', description: 'Torre de hotcakes con fruta y toppings', price: '$175', tag: 'signature', featured: true },
    { id: 'm5', categoryId: 'dulce', name: 'French toast', description: 'Opción dulce muy alineada con la línea de desayuno casero y pan del día', price: '$170' },
    { id: 'm6', categoryId: 'salado', name: 'Chapata bomba', description: 'Sándwich fuerte de mañana, inspirado en recomendaciones públicas de Coffee St Fitz', price: '$165' },
    { id: 'm7', categoryId: 'salado', name: 'Toast de aguacate', description: 'Pan artesanal, aguacate y toque cítrico', price: '$150', tag: 'popular' },
    { id: 'm8', categoryId: 'salado', name: 'Chilaquiles con tasajo', description: 'Plato alineado con publicaciones recientes de la marca para empezar el día con más antojo', price: '$160' },
    { id: 'm9', categoryId: 'cafe', name: 'Latte', description: 'Espresso con leche vaporizada', price: '$78', tag: 'signature' },
    { id: 'm10', categoryId: 'cafe', name: 'Cold brew', description: 'Extracción en frío, perfil suave y refrescante', price: '$85' },
    { id: 'm11', categoryId: 'frias', name: 'Smoothie de frutos rojos', description: 'Mezcla frutal fresca para acompañar el desayuno', price: '$95' },
    { id: 'm12', categoryId: 'frias', name: 'Jugo verde', description: 'Jugo natural con perfil fresco y ligero', price: '$89' },
  ],
  promotions: [
    { id: 'p1', title: 'Desayuno Americano', description: 'Coffee St Fitz promocionó recientemente su Desayuno Americano con 2 hot cakes, tiras de tocino y 2 huevos al gusto.', badge: 'Nuevo en menú', ctaLabel: 'Explorar menú', ctaAction: 'link', ctaValue: '/menu' },
    { id: 'p2', title: 'Pedidos fuera del local', description: 'La comunicación pública también impulsa pedidos cuando no hay tiempo de salir a desayunar.', badge: 'Pide fácil', ctaLabel: 'Escríbenos', ctaAction: 'whatsapp' },
    { id: 'p3', title: 'Pan recién horneado y brunch casual', description: 'La marca se presenta públicamente como un lugar de desayunos, café y pan recién horneado para una mañana relajada.', badge: 'Favoritos', ctaLabel: 'Cómo llegar', ctaAction: 'link', ctaValue: 'https://maps.google.com/maps/place//data=!4m2!3m1!1s0x8f5677e63382587b:0xe9cec5c746b63b94?entry=s&sa=X&ved=2ahUKEwigzpD3nv2TAxVKGYYAHapjCVMQ4kB6BAgEEAA&hl=en' },
  ],
  gallery: [
    { id: 'g1', src: 'https://pplx-res.cloudinary.com/image/upload/pplx_search_images/984d96b8440003663a02cc4c06a9f5c42733c74e.jpg', alt: 'Desayuno servido en mesa', caption: 'Mañanas completas', category: 'food' },
    { id: 'g2', src: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&auto=format&fit=crop&q=80', alt: 'Barra de café y preparación', caption: 'Café de todos los días', category: 'drinks' },
    { id: 'g3', src: 'https://pplx-res.cloudinary.com/image/upload/pplx_search_images/b31c8df54ebde65934f8b6c1545090b7b2222054.jpg', alt: 'Taza de café en mesa luminosa', caption: 'Pausa y café', category: 'drinks' },
    { id: 'g4', src: 'https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?w=800&auto=format&fit=crop&q=80', alt: 'Plato de brunch con huevo y pan', caption: 'Brunch casual', category: 'food' },
    { id: 'g5', src: 'https://pplx-res.cloudinary.com/image/upload/pplx_search_images/1fd6971e568b92e044c950cb1cfb71f2c6d6c4ae.jpg', alt: 'Interior de cafetería moderna', caption: 'Espacio para quedarte', category: 'interior' },
    { id: 'g6', src: 'https://pplx-res.cloudinary.com/image/upload/pplx_search_images/868abcd5b9188a785f9c6e572859ef4b3a75aae1.jpg', alt: 'Interior acogedor de cafetería', caption: 'Ambiente social', category: 'interior' },
  ],
  testimonials: [
    { id: 't1', name: 'Reseña pública', source: 'TripAdvisor', rating: 5, text: 'Buen lugar para desayunar, con carta variada donde predominan los platos con huevos y variedad de jugos.', date: '2019' },
    { id: 't2', name: 'Reseña pública', source: 'TripAdvisor', rating: 5, text: 'Coffee Saint Fitz es buenísimo para desayunar como campeón; recomiendan mucho los huevos motuleños y los jugos naturales.', date: '2018' },
    { id: 't3', name: 'Perfil público', source: 'Instagram', rating: 5, text: 'Desayunos, comidas, jugos, cafés y pan recién horneado, todo en un solo lugar.', date: '2026' },
  ],
  faqs: [
    { question: '¿Qué ofrece Coffee St Fitz?', answer: 'La marca comunica desayunos, comidas, jugos, cafés y pan recién horneado, además de opciones como chilaquiles, chapatas, omelettes y platillos dulces.' },
    { question: '¿Cuál es el horario de referencia en este sitio?', answer: 'Tomamos como referencia el horario público mostrado por listados y reseñas: lunes a sábado de 7:30 a.m. a 2:30 p.m. y domingo de 8:00 a.m. a 2:00 p.m.' },
    { question: '¿Cómo puedo contactarlos?', answer: 'Instagram público muestra el teléfono 9991582029 y la marca mantiene comunicación activa en redes sociales.' },
    { question: '¿El sitio puede servir para pedidos?', answer: 'Sí. Este starter puede iniciar con flujo mock de pedido o contacto y luego conectarse a WhatsApp o a un sistema real de pedidos.' },
  ],
  reservation: {
    enabled: true,
    mode: 'mock',
    maxGuests: 8,
    minAdvanceHours: 1,
    modalTitle: 'Contacto rápido Coffee St Fitz',
    modalDescription: 'Completa el formulario y genera un mensaje listo para continuar por WhatsApp.',
    successTitle: '¡Solicitud lista!',
    successDescription: 'Tu mensaje quedó preparado para continuar por WhatsApp.',
    previewLabel: 'Vista previa del mensaje',
    openWhatsappLabel: 'Abrir conversación',
    messageTemplate: 'Hola Coffee St Fitz Mérida 👋 Quisiera información sobre menú, pedido o visita para *{{guests}} personas* el *{{date}}* a las *{{time}}*. Mi nombre es *{{name}}*.',
    whatsappNumber: '529991582029',
  },
  whatsapp: {
    number: '529991582029',
    defaultMessage: 'Hola Coffee St Fitz, quisiera información sobre menú, sucursal u horario.',
    floatingButton: true,
    ariaLabel: 'Contactar por WhatsApp',
  },
  location: {
    address: 'Sucursal Mérida (ubicación del enlace compartido)',
    city: 'Mérida',
    state: 'Yucatán',
    zip: '97120',
    country: 'México',
    googleMapsUrl: 'https://maps.google.com/maps/place//data=!4m2!3m1!1s0x8f5677e63382587b:0xe9cec5c746b63b94?entry=s&sa=X&ved=2ahUKEwigzpD3nv2TAxVKGYYAHapjCVMQ4kB6BAgEEAA&hl=en',
    mapAriaLabel: 'Mapa de ubicación Coffee St Fitz en Mérida',
    mapImageAlt: 'Ubicación referencial de Coffee St Fitz en Mérida, Yucatán',
    openMapsLabel: 'Abrir ubicación',
    hoursTitle: 'Horario publicado',
    hours: [
      { day: 'Lunes', hours: '7:30 am – 2:30 pm' },
      { day: 'Martes', hours: '7:30 am – 2:30 pm' },
      { day: 'Miércoles', hours: '7:30 am – 2:30 pm' },
      { day: 'Jueves', hours: '7:30 am – 2:30 pm' },
      { day: 'Viernes', hours: '7:30 am – 2:30 pm' },
      { day: 'Sábado', hours: '7:30 am – 2:30 pm' },
      { day: 'Domingo', hours: '8:00 am – 2:00 pm' },
    ],
    phone: '+52 999 158 2029',
    email: 'contacto@coffeestfitz.com',
  },
  social: {
    instagram: 'https://www.instagram.com/coffee_st_fitz/',
    facebook: 'https://www.facebook.com/coffeestfitz/',
  },
};
